### ISSUE TITLE
Update README.md with dockerhub image ?

### ISSUE THREAD

**Issue by yetanotherjr** [dubo-dubon-duponey/docker-spotify#13]
Hello !

Could you update the examples in README.md, with the correct image location ?

Currently: `ghcr.io/dubo-dubon-duponey/spotify`
Should be (after following the "about" link): `docker.io/dubodubonduponey/librespot`

Thanks !

**Comment by dubo-dubon-duponey** [comment]
Hey there @yetanotherjr 

Lately, I have had issues with Docker Hub - rate limiting, blocking pushes, push timeouts.

I still try to also push to Docker Hub of course, but really, ghcr is my main goto these days.
Do you have any issues with the ghcr versions?

**Comment by yetanotherjr** [comment]
Indeed, I'm using docker compose and get this every time:
```
 ⠿ librespot Error                                                                                                                      0.3s
Error response from daemon: Head "https://ghcr.io/v2/dubo-dubon-duponey/spotify/manifests/latest": unauthorized
```

docker-compose.yml
```yaml
version: '3'
services:
  librespot:
    container_name: librespot
#    image: dubodubonduponey/librespot
    image: ghcr.io/dubo-dubon-duponey/spotify
    volumes:
      - /data/docker/librespot/storage/tmp:/tmp
    devices:
      - /dev/snd:/dev/snd
    restart: unless-stopped
    network_mode: host
    environment:
      - NAME=srv.lan
    cap_drop:
      - ALL
    group_add:
      - "29"
    ports:
      - 10042:10042
    command: librespot --initial-volume 100 --enable-volume-normalisation --device hw:CARD=Device
    healthcheck:
      disable: true

```

When trying to access the URL directly, it shows a 404 page
